### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by jhautefeuille** [hgsigner/gootstrap#2]
julien@tarte:~/ownCloud/Codingᛤ $GOPATH/bin/gootstrap new usine
===> Creating package usine
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18]

goroutine 1 [running]:
main.Parse.N18_main.GitIgnoreFile
	/home/julien/go/src/github.com/hgsigner/gootstrap/templates.go:25
main.createFile.N13_main.gootFile
	/home/julien/go/src/github.com/hgsigner/gootstrap/goot_file.go:69
main.createOrErrorOut
	/home/julien/go/src/github.com/hgsigner/gootstrap/goot_file.go:106
main.performCreation.N13_main.gootFile
	/home/julien/go/src/github.com/hgsigner/gootstrap/goot_file.go:85
main.Process.N14_main.filesList
	/home/julien/go/src/github.com/hgsigner/gootstrap/goot_file.go:23
main.createPackage
	/home/julien/go/src/github.com/hgsigner/gootstrap/gootstrap.go:155
main.runCommand
	/home/julien/go/src/github.com/hgsigner/gootstrap/gootstrap.go:61
main.run
	/home/julien/go/src/github.com/hgsigner/gootstrap/gootstrap.go:28
main.main
	/home/julien/go/src/github.com/hgsigner/gootstrap/gootstrap.go:70

**Comment by hgsigner** [comment]
Hi,

`go get github.com/hgsigner/gootstrap` again. I fixed this bug. Let me know if it works.

**Comment by jhautefeuille** [comment]
Good, it works !

julien@dunkerque:~/ownCloud/Codingᛤ $GOPATH/bin/gootstrap new usine2
===> Creating package usine2
===> Creating .gitignore file
===> Creating .travis.yml file
===> Creating LICENSE.txt file
===> Creating README.md file
===> Creating usine2.go file
===> Creating usine2_test.go file
===> Creating doc.go file
===> Creating CHANGELOG.md file
===> Package created! cd usine2 to access.

Thank you
